
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktwjilsqeiawmivzdusl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0d2ppbHNxZWlhd21pdnpkdXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzc3NzIsImV4cCI6MjA1OTk1Mzc3Mn0.nnTT3mkoShhqWPZWS7cMjRvkpJDJ4J7L37IRihf5zGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
